#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# cd 5.\ Smart\ contract\ Solidity\ \&\ bonnes\ pratiques\ de\ sécurité/
# yarn prettier:solidity
# git add contracts/.
# yarn docgen
# git add docs/.
# yarn test

# publish documentation storybookw
cd 8.\ NFT/client
# yarn run chromatic --auto-accept-changes

# truffle projet
cd ../truffle/
# lint
# yarn prettier:solidity
git add contracts/.
# testing
# yarn test
# generate solidity documentation
# yarn docgen
# git add ../client/src/docs/